export type {
  Align,
  ButtonBlock,
  ButtonTag,
  CssValue,
  IconBlock,
  ImageBlock,
  LinkTarget,
  NavsBlock,
  PageBlock,
  PageData,
  PageDocument,
  PageGroup,
  PageGroupStyle,
  PageGroupType,
  RichTextBlock,
  RichTextType,
} from "../src/plugin/schema/page.types";
